server:
  port: 8080
  servlet:
    context-path: ''
  tomcat:
    max-threads: 20
  compression:
    enabled: true

spring:
  profiles:
    active: dev
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  datasource:
    # 初始化数据导入
    schema: classpath*:db/install-h2.sql
    data: classpath*:db/data.sql
    sql-script-encoding: utf-8
    initialization-mode: never
    continue-on-error: true
    # 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 3 # 初始化大小
      minIdle: 3 #最小连接池数量
      maxActive: 20 #最大连接池数量
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 #验证连接有效与否的SQL
      testWhileIdle: true #不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      filters: stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    # h2 内存数据库 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${mfile.db.path};MODE=MYSQL;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=FALSE
    username: mfile
    password: 123456
    # MySQL 配置
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://127.0.0.1:3306/mfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
  #    username: root
  #    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  resources:
    chain:
      gzipped: true

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    cache-enabled: true  #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    callSettersOnNulls: true
  global-config:
    banner: false
    db-config:
      id-type: AUTO   #数据库自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: ml.lwei.mfile.model.entity   # 实体扫描，多个package用逗号或者分号分隔
  typeEnumsPackage: ml.lwei.mfile.model.enums


mfile:
  log:
    path: ${user.home}/.mfile/logs
  db:
    # C:/Users/wei3.liu/.mfile/db/mfile;MODE=MYSQL;AUTO_SERVER=TRUE
    path: ${user.home}/.mfile/db/mfile
  tmp:
    path: ${user.home}/.mfile/tmp
  cache:
    auto-refresh:
      interval: 1
    timeout: 1800
  constant:
    readme: readme.md
    password: password.txt
  preview:
      audio:
          maxFileSizeMb: 5
      text:
          maxFileSizeKb: 512

